---
- name: configure pacman
  block:
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#Color'
        line: 'Color'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#UseSyslog'
        line: 'UseSyslog'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#CheckSpace'
        line: 'CheckSpace'
    - lineinfile:
        path: /etc/pacman.conf
        regexp: '#ILoveCandy'
        line: 'ILoveCandy'
        insertafter: '# Misc options'

- name: Update lists and upgrade
  tags: pacman-update
  pacman:
    update_cache: yes
    upgrade: yes

# - name: Configure reflector
#   copy:
#     src: reflector.conf
#     dest: /etc/xdg/reflector/
#   notify: enable reflector

- name: Install pacman hooks and fakeroot
  pacman:
    name:
      - kernel-modules-hook # keep kernel modules dir after an upgrade
      - fakeroot # superuser privileges, dep for makepkg
