---
- name: install containers packages
  become: yes # TODO: workaround - should be avoided
  pacman:
    name:
      - docker          # high level container runtime
      - docker-compose  # multi-container docker apps

- name: Add user to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
