---
- name: install desktop packages
  pacman:
    name:
      - sway
      - swaybg
      - xorg-server-xwayland
      - waybar
      - mako # notification daemon
      - kanshi # autorandr for wayland
      - grim # screenshots
      - slurp # region selector
      - wl-clipboard # clipboard manager
      - brightnessctl # brightness manager
      - wofi # rofi for wayland
      - swayidle
      - xdg-user-dirs
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      # - vulkan-intel
      # - lib32-vulkan-intel
      # - intel-media-driver
      # - libva-utils
    state: present

- name: install audio packages
  pacman:
    name:
      - pipewire
      - pipewire-pulse
      - wireplumber
      - pavucontrol
      - pamixer
      - alsa-utils
    state: present

- name: install applications packages
  pacman:
    name:
      - imv # img visualizer
      - kitty # terminal emulator
      - evince # pdf viewer
      - evolution # mail client
      - gnome-keyring # evolution gnome keyring
      - seahorse # keyring manager
      - firefox
      - gimp # img editor
      - kolourpaint # img editor
      - shotwell # photo manager
      - lollypop # music player
      - lxappearance # theme manager
      - mpv # video player
      - thunar # file manager
      - tumbler # thumbnailer
      - openvpn
      - playerctl # music player cli controller
      - transmission-gtk # torrent downloader
      - texlive-bin # latex
      - texlive-core # latex
      - texlive-latexextra # latex
      - texlive-fontsextra # latex
      - variety # random backgrounds
      - papirus-icon-theme # icon theme
      - gnome-themes-extra # gtk themes
      - youtube-dl
      - gopass # password manager
      - wf-recorder # screen recorder for wayland
    state: present

- name: install aur packages
  become: no
  kewlfft.aur.aur:
    state: present
    name:
      - adapta-gtk-theme #https://github.com/Alexays/Waybar/issues/515
      - equilux-theme 
      - swaylock-fancy-git # locker for wayland
      - chromium
      - lf # cli file manager
      - otf-font-awesome-5
      - swappy # screenshot editor
